name: Deploy Django App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      SPOTIPY_CLIENT_ID: ${{secrets.SPOTIPY_CLIENT_ID }}
      SPOTIPY_CLIENT_SECRET: ${{secrets.SPOTIPY_CLIENT_SECRET }}
      SPOTIPY_REDIRECT_URL:  ${{secrets.SPOTIPY_REDIRECT_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.x

      - name: Create virtual environment
        run: |
          python -m env myenv
          source myenv/bin/activate
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Database migrations
        run: python manage.py migrate

      - name: Collect static files
        run: python manage.py collectstatic --no-input

      - name: Start Django app
        run: gunicorn myproject.wsgi:application
